### ISSUE TITLE
JSON-RPC method to set auth in SuperstarV2

### ISSUE THREAD

**Issue by FineTralfazz** [robotmoose/robotmoose#112] opened 2016-07-20 07:54 UTC
Arsh implemented it in v1 as part of #38, but it doesn't exist in v2 (or at least isn't part of the documentation, I haven't looked through the code).

**Comment by mrmoss** [comment] 2016-07-20 08:18
The old set auth didn't work as needed (only added new auths, never removed original auth). It was put on hold until this server was tested and such. I'd call this a duplicate of #38.

**Closed as completed by mrmoss** 2016-07-20 08:18 UTC
Labels: duplicate, enhancement
